apiVersion: v1
kind: Pod
metadata:
  name: myconfig-map-demo
spec:
  containers:
  - name: configmap-demo
    image: alpine 
    command: ["sleep", "3000"]
    env:
      - name: PLAYER_LIVE
        valueFrom:
          configMapKeyRef:
            name: player-pro-demo
            key: player_live
      - name: PROPERTIES_FILE_NAME 
        valueFrom:
          configMapKeyRef:
            name: player-pro-demo
            key: properties_file_name
      - name: FILE
        valueFrom:
          configMapKeyRef:
            name: player-pro-demo
            key: file
      - name: SECRET_DATA
        valueFrom:
          secretKeyRef:
            key: username
            name: secret-demo 

