apiVersion: v1
kind: Pod
metadata:
  name: mysql-demo
spec:
  containers:
    - name: mysql-posix
      image: mysql:latest
      ports:
        - containerPort: 3306
      envFrom:
        - configMapRef:
            name: posix-mysql-demo